server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/userdb
    username: root
    password: netect123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  package-ot-scan: com.ms.user.controller
control:
  exception:
    personalizada: Se genero un error de negocio
    system: Se genero un error del sistema